# Generated by Django 4.0.5 on 2022-07-05 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_song_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_file',
            field=models.FileField(blank=True, null=True, upload_to='article_files/'),
        ),
    ]
